name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3.1.2
      with:
        python-version: 3.11

    - name: Install module in venv
      run: make setup

    - name: Run tests
      run: make test

    - name: Run linters
      run: make lint
