name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3.1.2
      with:
        python-version: 3.11

    - name: Install module in venv
      run: make setup

    - name: Run tests
      run: make test

    - name: Run linters
      run: make lint

    - name: Run coverage
      run: make coverage

    - name: Commit coverage
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add coverage-badge.svg
        git commit -m "Update coverage badge"
        git push
